### ISSUE TITLE
Action globale: home_defence_mode

### ISSUE THREAD

**Issue by kaleofr** [Famille-OZAER/jeezvizv2#4]
Bonjour,
Sur ma Caméra C3X, l'action follow_move ne semble pas modifier quoi que ce soit.
Par contre, la commande home_defence_mode fonctionne parfaitement pour activer la détection sur l'ensemble des devices.
Serait-il possible d'ajouter les deux actions:
pyezviz -u USER -p PASSWORD home_defence_mode --mode HOME_MODE
et
pyezviz -u USER -p PASSWORD home_defence_mode --mode AWAY_MODE
En attendant, je fais ca avec un script mais tout intégrer serait plus "propre".

Kaléo.

**Comment by OOZAER** [comment]
Bonjour,

J'ai ajouté les deux commandes.

Cependant, je ne peux pas les tester, mon compte Ezviz est bloqué pour l'instant.

Dis moi si c'est bon :)

Dans la bêta de ce soir.

**Comment by OOZAER** [comment]
Bonjour,

J'ai vérifié ce matin, et apporté quelques corrections.

Les commandes retournent bien ok mais je ne sais pas comment le vérifier
Sais-tu quel paramètre dans l'application smartphone doit se modifier ?

Concernant le follow_move, j'ai une exception pour ma part dans les logs, je pense que ma caméra ne doit pas le supporter, je creuserai plus ce soir.

Bonne journée
Olivier

**Comment by kaleofr** [comment]
Ca fonctionne parfaitement! Merci!
Cela active un petit bouclier: Mode et routines: Vos appareils de sécurité sont armés 
Ca affiche sur l'image de la caméra Alarme activée ou Alarme déactivée.

C'est parfait!
Bonne journée,

Philippe.

**Comment by OOZAER** [comment]
Merci du retour et des infos.

Je cloture.

Bonne fin de journée
Olivier
