### ISSUE TITLE
Coche "Afficher" pour les commandes actions et info

### ISSUE THREAD

**Issue by kaleofr** [Famille-OZAER/jeezvizv2#6]
Le plugin fournit beaucoup de commandes (actions et infos)
Certaines ne sont d'ailleurs pas souvent utiles ou parfois non présente (Ma caméra n'est pas PTZ par exemple).
Pour rendre l'affichage plus lisible, l'ajout de la coche "Afficher" pour chaque commande serait la bienvenue.

Qu'en dites vous?

Kaléo

**Comment by OOZAER** [comment]
Bonsoir,
J'ai apporté l'évolution demandée.

Au passage, j'ai ajouté la possibilité d'activer ou non l'historisation.

Dans la bêta de ce soir

Bonne soirée

**Comment by kaleofr** [comment]
Super merci!
