### ISSUE TITLE
[Évolution] Basculer en stable sur Jeedom

### ISSUE THREAD

**Issue by chris777c** [Famille-OZAER/jeezvizv2#7]
Bonjour,

Avez vous prévu de basculer en stable le plugin ?

Cordialement

**Comment by chris777c** [comment]
Bonjour, 
un petit up au cas où.

**Comment by OOZAER** [comment]
Bonjour,

Ce n'est pas prévu à court terme.
Les démarches me semblent trop contraignant pour le faire.

Cordialement
