### ISSUE TITLE
Comaptibilité visiophone HP7 ezviz

### ISSUE THREAD

**Issue by razmoket89** [Famille-OZAER/jeezvizv2#8]
Bonjour, 

Avant de passer à l'achat, je souhaite juste m'assurer que le visiophone HP7 de chez ezviz est bien supporté par ce plugin, notamment la partie contrôle des relais d'ouverture. La partie caméra ne m'intéresse pas.

Merci.

**Comment by OOZAER** [comment]
Bonjour,Je ne sais pas te répondre.J'ai développé le plugin en testant uniquement avec ma propre camera.Cordialement Envoyé à partir de Outlook pour Android
